type R=Record<string,any>;
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const deadline=async(url:string,init?:RequestInit)=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(t)}};
async function mapLimit<T,R>(items:T[],limit:number,fn:(item:T)=>Promise<R>){const out:R[]=[];for(let i=0;i<items.length;i+=limit)out.push(...await Promise.all(items.slice(i,i+limit).map(fn)));return out}
const empty=(venue:string,error:string)=>({venue,ok:false,coverage:"unavailable",error,trackedTraders:0,longNotional:0,shortNotional:0,positions:0,coins:[]});
function aggregate(venue:string,trackedTraders:number,raw:R[]){const map=new Map<string,{symbol:string;longNotional:number;shortNotional:number;longTraders:Set<string>;shortTraders:Set<string>;positions:number}>();let longNotional=0,shortNotional=0,positions=0;for(const p of raw){const value=Math.abs(n(p.value)),side=String(p.side).toUpperCase(),symbol=String(p.symbol||"?");if(!value||!symbol)continue;const row=map.get(symbol)??{symbol,longNotional:0,shortNotional:0,longTraders:new Set(),shortTraders:new Set(),positions:0};if(side==="LONG"){row.longNotional+=value;longNotional+=value;row.longTraders.add(p.trader)}else{row.shortNotional+=value;shortNotional+=value;row.shortTraders.add(p.trader)}row.positions++;positions++;map.set(symbol,row)}return{venue,ok:true,coverage:"top-traders",trackedTraders,longNotional,shortNotional,positions,coins:[...map.values()].map(x=>({symbol:x.symbol,longNotional:x.longNotional,shortNotional:x.shortNotional,longTraders:x.longTraders.size,shortTraders:x.shortTraders.size,positions:x.positions})).sort((a,b)=>(b.longNotional+b.shortNotional)-(a.longNotional+a.shortNotional)).slice(0,25)}}
async function hyperliquid(){try{const lr=await deadline("https://stats-data.hyperliquid.xyz/Mainnet/leaderboard");if(!lr.ok)throw new Error(`Leaderboard HTTP ${lr.status}`);const payload=await lr.json() as R;const addresses=(payload.leaderboardRows??[]).map((x:R)=>({address:String(x.ethAddress),pnl:n((x.windowPerformances??[]).find((w:R[])=>w[0]==="month")?.[1]?.pnl)})).sort((a:R,b:R)=>b.pnl-a.pnl).slice(0,12).map((x:R)=>x.address);const states=await mapLimit(addresses,4,async(address:string)=>{try{const r=await deadline("https://api.hyperliquid.xyz/info",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"clearinghouseState",user:address})});return r.ok?{address,data:await r.json()}:null}catch{return null}});const raw:R[]=[];for(const item of states){if(!item)continue;for(const row of item.data.assetPositions??[]){const p=row.position??row,sz=n(p.szi);if(!sz)continue;raw.push({trader:item.address,symbol:p.coin,side:sz>0?"LONG":"SHORT",value:Math.abs(n(p.positionValue))})}}return aggregate("Hyperliquid",states.filter(Boolean).length,raw)}catch(error){return empty("Hyperliquid",error instanceof Error?error.message:"Unavailable")}}
async function arcus(){try{const lr=await deadline("https://api.arcus.xyz/v1/leaderboard?window=30d&sortBy=pnl&limit=8");if(!lr.ok)throw new Error(`Leaderboard HTTP ${lr.status}`);const p=await lr.json() as R,addresses=(p.entries??[]).map((x:R)=>String(x.address)).filter(Boolean).slice(0,8);const states=await mapLimit(addresses,4,async(address:string)=>{try{const r=await deadline(`https://api.arcus.xyz/v1/positions?address=${address}`);return r.ok?{address,data:await r.json()}:null}catch{return null}});const raw:R[]=[];for(const item of states){if(!item)continue;for(const p of Object.values(item.data.positions??{}) as R[]){const size=n(p.size??p.positionSize),value=Math.abs(n(p.notional??p.positionValue));if(!size&&!value)continue;raw.push({trader:item.address,symbol:p.marketDisplayName??p.market??p.marketId,side:String(p.side??(size>=0?"LONG":"SHORT")),value})}}return aggregate("Arcus Perps",states.filter(Boolean).length,raw)}catch(error){return empty("Arcus Perps",error instanceof Error?error.message:"Unavailable")}}
export async function GET(){const hl=await hyperliquid(),arcus=await arcus();return Response.json({generatedAt:new Date().toISOString(),methodology:"Open positions of top monthly-PnL public leaderboard traders",venues:[hl,empty("Lighter","No public trader-discovery leaderboard"),empty("Lighter · Robinhood","No public trader-discovery leaderboard"),empty("SoDEX","No public trader-discovery leaderboard"),arcus,empty("Perpl","No public trader-discovery leaderboard")]},{headers:{"cache-control":"public, s-maxage=120, stale-while-revalidate=300"}})}
