"use client";

import { useEffect, useMemo, useState } from "react";

type VenueName="Hyperliquid"|"Lighter"|"Lighter · Robinhood"|"SoDEX"|"Arcus Perps"|"Perpl";
type Market = { symbol:string; venue:VenueName; price:number; change:number; volume:number; oi:number; funding:number; spark:number[] };
const venueMeta:{name:VenueName;network:string;code:string}[]=[
  {name:"Hyperliquid",network:"HyperCore",code:"H"},{name:"Lighter",network:"Ethereum · USDC",code:"L"},{name:"Lighter · Robinhood",network:"Robinhood · USDG",code:"R"},{name:"SoDEX",network:"ValueChain · vUSDC",code:"S"},{name:"Arcus Perps",network:"Robinhood · USDG",code:"A"},{name:"Perpl",network:"Monad · USDC",code:"P"},
];
const markets: Market[] = [
  {symbol:"BTC",venue:"Hyperliquid",price:117842,change:2.84,volume:3280000000,oi:1740000000,funding:.0081,spark:[34,38,35,43,46,44,52,49,57,61,59,67]},
  {symbol:"ETH",venue:"Hyperliquid",price:4482.6,change:4.12,volume:2140000000,oi:1180000000,funding:.0064,spark:[28,31,29,36,33,42,39,48,51,49,55,63]},
  {symbol:"BTC",venue:"Lighter",price:117816,change:2.78,volume:472000000,oi:218000000,funding:.0079,spark:[31,34,33,38,42,40,47,45,51,55,53,60]},
  {symbol:"SOL",venue:"Hyperliquid",price:196.84,change:5.37,volume:918000000,oi:462000000,funding:.0124,spark:[25,29,26,34,31,39,44,41,50,47,56,64]},
  {symbol:"ETH",venue:"Lighter",price:4480.9,change:4.05,volume:326000000,oi:164000000,funding:.0061,spark:[27,30,29,35,34,40,38,46,49,47,54,61]},
  {symbol:"HYPE",venue:"Hyperliquid",price:48.36,change:-1.46,volume:184000000,oi:136000000,funding:-.0042,spark:[62,58,61,54,56,49,52,46,43,47,41,38]},
  {symbol:"SOL",venue:"Lighter",price:196.77,change:5.31,volume:112000000,oi:72000000,funding:.0118,spark:[24,27,26,32,30,37,41,39,47,45,53,60]},
  {symbol:"DOGE",venue:"Lighter",price:.2384,change:-.82,volume:68000000,oi:41000000,funding:-.0016,spark:[56,52,55,50,51,47,49,44,46,42,43,39]},
];
const money=(v:number)=>v>=1e9?`$${(v/1e9).toFixed(2)}B`:`$${(v/1e6).toFixed(0)}M`;
const price=(v:number)=>v<1?`$${v.toFixed(4)}`:v<1000?`$${v.toLocaleString("en-US",{maximumFractionDigits:2})}`:`$${v.toLocaleString("en-US",{maximumFractionDigits:1})}`;

function Sparkline({points,positive}:{points:number[];positive:boolean}){const coords=points.map((p,i)=>`${i/(points.length-1)*100},${70-p}`).join(" ");return <svg className={`spark ${positive?"up":"down"}`} viewBox="0 0 100 48" preserveAspectRatio="none"><polyline points={coords}/></svg>}

export default function Home(){
  const [venue,setVenue]=useState("All venues"),[query,setQuery]=useState(""),[sort,setSort]=useState<"volume"|"change">("volume");
  const [watchlist,setWatchlist]=useState(["BTC-Hyperliquid"]);
  const [marketData,setMarketData]=useState(markets);
  const [dataMode,setDataMode]=useState<"loading"|"live"|"snapshot">("loading");
  const [venueStatus,setVenueStatus]=useState<Record<string,{ok:boolean;error?:string}>>({});
  const [positioning,setPositioning]=useState<Record<string,any>>({});
  const [positionLoading,setPositionLoading]=useState(true);
  useEffect(()=>{fetch("/api/markets").then(r=>r.ok?r.json():Promise.reject()).then(payload=>{
    setVenueStatus(Object.fromEntries((payload.venues??[]).map((v:{venue:string;ok:boolean;error?:string})=>[v.venue,v])));
    if(!Array.isArray(payload.markets)||!payload.markets.length) throw new Error("No markets");
    const normalized:Market[]=payload.markets.filter((m:Market)=>m.price>0).map((m:Market)=>({...m,spark:m.spark??(m.change>=0?[30,34,32,39,42,40,47,45,52,55,53,61]:[61,57,59,53,55,48,51,44,46,41,43,37])}));
    if(!normalized.length) throw new Error("No priced markets"); setMarketData(normalized);setDataMode("live");
  }).catch(()=>setDataMode("snapshot"))},[]);
  useEffect(()=>{fetch("/api/positioning").then(r=>r.ok?r.json():Promise.reject()).then(p=>setPositioning(Object.fromEntries((p.venues??[]).map((v:any)=>[v.venue,v])))).catch(()=>setPositioning({})).finally(()=>setPositionLoading(false))},[]);
  const filtered=useMemo(()=>marketData.filter(m=>(venue==="All venues"||m.venue===venue)&&m.symbol.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="volume"?b.volume-a.volume:b.change-a.change),[venue,query,sort,marketData]);
  const summaries=useMemo(()=>venueMeta.map(meta=>{const rows=marketData.filter(m=>m.venue===meta.name);return{...meta,rows,volume:rows.reduce((s,m)=>s+m.volume,0),oi:rows.reduce((s,m)=>s+m.oi,0),status:venueStatus[meta.name],position:positioning[meta.name]}}),[marketData,venueStatus,positioning]);
  const totals=useMemo(()=>({volume:marketData.reduce((s,m)=>s+m.volume,0),oi:marketData.reduce((s,m)=>s+m.oi,0),markets:marketData.length,venues:summaries.filter(s=>s.rows.length).length,positions:summaries.reduce((n,s)=>n+(s.position?.positions??0),0),tracked:summaries.reduce((n,s)=>n+(s.position?.trackedTraders??0),0)}),[marketData,summaries]);
  const selectedSummary=summaries.find(s=>s.name===venue);
  const toggle=(m:Market)=>{const key=`${m.symbol}-${m.venue}`;setWatchlist(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key])};
  return <main>
    <header className="topbar"><a className="brand" href="#"><span className="brand-mark"><i/><i/><i/></span><span>OPEN PERPS</span><em>TERMINAL</em></a><nav><a className="active" href="#markets">Markets</a><a href="#compare">Compare</a><a href="/wallet">Wallet analyzer</a><a href="#about">About</a></nav><div className="header-actions"><span className={`live ${dataMode}`}><i/> {dataMode==="live"?"Live data":dataMode==="loading"?"Connecting":"Demo snapshot"}</span><a className="github" href="https://github.com/CPredecessor/open-perps-terminal" target="_blank" rel="noreferrer">GitHub ↗</a></div></header>
    <div className="shell">
      <section className="intro"><div><p className="eyebrow">CROSS-DEX OPEN POSITION INTELLIGENCE</p><h1>Longs versus shorts.<br/><span>Venue-level detail.</span></h1><p className="lede">Compare open long and short notional held by discoverable top traders, then open a venue for coin-level positioning.</p></div><div className="status-card"><div><span>DATA STATUS</span><strong><i/> {dataMode==="live"?"Public APIs connected":dataMode==="loading"?"Connecting to venues":"Fallback snapshot active"}</strong></div><div className="status-row"><span>Venues <b>{totals.venues} / 6 live</b></span><span>Markets <b>{totals.markets} loaded</b></span></div><small>Public positions only · unavailable leaderboards are never estimated</small></div></section>
      <section className="metric-grid"><article><span>COMBINED 24H VOLUME</span><strong>{money(totals.volume)}</strong><small>Verified venue responses</small><div className="mini-bars"><i/><i/><i/><i/><i/><i/><i/><i/></div></article><article><span>COMBINED OPEN INTEREST</span><strong>{money(totals.oi)}</strong><small>Across loaded perp markets</small><div className="metric-line"/></article><article><span>SCANNED OPEN POSITIONS</span><strong>{totals.positions}</strong><small>From {totals.tracked} discoverable top traders</small><div className="protocol-dots"><i className="hl"/>LONG <i className="li"/>SHORT</div></article><article><span>CONNECTED VENUES</span><strong>{totals.venues} / 6</strong><small>No unavailable metric is estimated</small><div className="funding-scale"><i style={{width:`${totals.venues/6*100}%`}}/><b style={{left:`${totals.venues/6*100}%`}}/></div></article></section>
      <section id="compare" className="venue-overview"><div className="overview-head"><div><p className="section-kicker">ALL VENUES</p><h2>Open position overview</h2></div><span>Select a venue for coin-level long / short detail</span></div><div className="overview-grid">{summaries.map(s=><VenueOverview key={s.name} summary={s} loading={positionLoading} selected={venue===s.name} onClick={()=>setVenue(venue===s.name?"All venues":s.name)}/>)}</div>{venue!=="All venues"&&<><div className="drilldown-banner"><div><span>ACTIVE VIEW</span><b>{venue}</b></div><p>{filtered.length} public markets · table below is filtered to this venue.</p><button onClick={()=>setVenue("All venues")}>Show all venues ×</button></div><PositionDetail data={selectedSummary?.position}/></>}</section>
      <section id="markets" className="markets-panel"><div className="panel-head"><div><p className="section-kicker">MARKET SCREENER</p><h2>Perpetual markets</h2></div><div className="filters"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search market" aria-label="Search market"/></label><select value={venue} onChange={e=>setVenue(e.target.value)}><option>All venues</option>{venueMeta.map(v=><option key={v.name}>{v.name}</option>)}</select><button onClick={()=>setSort(sort==="volume"?"change":"volume")}>Sort: {sort==="volume"?"Volume":"24h change"} ↕</button></div></div>
        <div className="table-wrap"><table><thead><tr><th></th><th>MARKET</th><th>VENUE</th><th>PRICE</th><th>24H</th><th>24H VOLUME</th><th>OPEN INTEREST</th><th>7D TREND</th></tr></thead><tbody>{filtered.map(m=>{const key=`${m.symbol}-${m.venue}`;return <tr key={key}><td><button className={`star ${watchlist.includes(key)?"saved":""}`} onClick={()=>toggle(m)}>★</button></td><td><div className="asset"><i>{m.symbol[0]}</i><b>{m.symbol}<small>-PERP</small></b></div></td><td><span className={`venue-tag ${m.venue==="Hyperliquid"?"tag-hl":"tag-li"}`}>{m.venue}</span></td><td className="number">{price(m.price)}</td><td className={m.change>=0?"positive":"negative"}>{m.change>=0?"+":""}{m.change.toFixed(2)}%</td><td className="number">{money(m.volume)}</td><td className="number muted">{money(m.oi)}</td><td><Sparkline points={m.spark} positive={m.change>=0}/></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty">This venue did not return public market rows.</div>}</div>
      </section>
      <section id="about" className="open-source"><div><p className="section-kicker">BUILT IN THE OPEN</p><h2>Market data should be<br/>public infrastructure.</h2></div><div><p>Open Perps normalizes public protocol data into one transparent interface. No paywall, no hidden scoring model, no trading custody.</p><div className="source-actions"><a href="https://github.com/CPredecessor/open-perps-terminal" target="_blank" rel="noreferrer">View source ↗</a><span>Apache-2.0</span><span>Community driven</span></div></div></section>
    </div><footer><span>OPEN PERPS TERMINAL · PUBLIC MVP</span><span>Data is informational, not financial advice.</span></footer>
  </main>
}

function VenueOverview({summary:s,loading,selected,onClick}:{summary:any;loading:boolean;selected:boolean;onClick:()=>void}){const loaded=s.rows.length>0,p=s.position,total=(p?.longNotional??0)+(p?.shortNotional??0),longShare=total?p.longNotional/total*100:0,waiting=loading&&!p;return <button className={`overview-card ${selected?"selected":""}`} onClick={onClick}><div className="oc-head"><i>{s.code}</i><span><b>{s.name}</b><small>{s.network}</small></span><em className={loaded?"online":"offline"}>● {loaded?"LIVE":s.status?.ok?"NO MARKETS":"UNAVAILABLE"}</em></div><div className="oc-stats"><span>OPEN LONG<b className="positive">{p?.ok?money(p.longNotional):"—"}</b></span><span>OPEN SHORT<b className="negative">{p?.ok?money(p.shortNotional):"—"}</b></span><span>POSITIONS<b>{p?.ok?p.positions:"—"}</b></span><span>TRADERS<b>{p?.ok?p.trackedTraders:"—"}</b></span></div><div className="funding-bias"><div><span>{p?.ok?`${longShare.toFixed(0)}% LONG`:waiting?"SCANNING POSITIONS":p?.error||"POSITION SCANNER UNAVAILABLE"}</span><span>{p?.ok?`${(100-longShare).toFixed(0)}% SHORT`:waiting?"PLEASE WAIT":"NO RATIO ESTIMATED"}</span></div><i><em style={{width:`${longShare}%`}}/><b style={{width:`${p?.ok?100-longShare:0}%`}}/></i></div><footer><span>{selected?"DETAIL OPEN":"OPEN DETAILS"}</span><b>→</b></footer></button>}
function PositionDetail({data}:{data:any}){if(!data?.ok)return <div className="position-unavailable"><b>POSITION DATA UNAVAILABLE</b><span>{data?.error||"This venue does not publish a discoverable top-trader leaderboard, so no long/short ratio is estimated."}</span></div>;return <div className="position-detail"><div className="pd-head"><b>TOP-TRADER OPEN POSITIONS</b><span>{data.trackedTraders} traders · {data.positions} positions</span></div>{data.coins.map((c:any)=>{const total=c.longNotional+c.shortNotional,long=total?c.longNotional/total*100:0;return <div className="position-row" key={c.symbol}><b>{c.symbol}</b><div className="position-split"><i style={{width:`${long}%`}}/><em style={{width:`${100-long}%`}}/></div><span className="long-value">{money(c.longNotional)}</span><span className="short-value">{money(c.shortNotional)}</span><small>{c.longTraders} / {c.shortTraders} traders</small></div>})}</div>}
